from collections.abc import Sequence
from typing import Annotated, Any

from langchain_core.messages import AnyMessage
from langgraph.graph import MessagesState
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


def merge_evidence_items(
    left: Sequence[dict[str, Any]] | None,
    right: Sequence[dict[str, Any]] | None,
) -> list[dict[str, Any]]:
    """Union evidence items by citation id, keeping first-seen order.

    Needed because analysts can run in the same LangGraph super-step (see
    ``analyst_concurrency_limit``) and each one writes a full snapshot of the
    shared ``EvidenceRegistry``. Without a reducer this channel is LastValue
    and two concurrent writes raise ``InvalidUpdateError``. Ids are unique per
    source (``EvidenceRegistry.register`` is locked), so a union by id merges
    the overlapping snapshots without dropping or duplicating a source.
    """
    merged: dict[str, dict[str, Any]] = {}
    for items in (left or (), right or ()):
        for item in items:
            key = str(item.get("id"))
            if key not in merged:
                merged[key] = item
    return list(merged.values())


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]
    evidence_items: Annotated[list[dict], merge_evidence_items]
    prefetched: Annotated[dict | None, "Pre-fetched ETF snapshot summary for context injection"]

    # Per-analyst private ReAct scratchpads. Analysts share the inherited
    # ``messages`` channel only when they run one at a time; with
    # ``analyst_concurrency_limit`` > 1 their tool-call turns would interleave
    # in a single list, so the router reads the wrong last message and ToolNode
    # executes another analyst's call. Channel names must stay in sync with
    # ``AnalystNodeSpec.messages_key`` in graph/analyst_execution.py.
    market_messages: Annotated[list[AnyMessage], add_messages]
    social_messages: Annotated[list[AnyMessage], add_messages]
    news_messages: Annotated[list[AnyMessage], add_messages]
    fundamentals_messages: Annotated[list[AnyMessage], add_messages]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    validation_report: Annotated[str, "Report-validator consistency check: name/number fixes applied after the final decision"]
